// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dopglvepsssfgybzlnkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcGdsdmVwc3NzZmd5YnpsbmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODc0NjcsImV4cCI6MjA2NDI2MzQ2N30.dYxdfBGT8flHus9zEC6HJOtWqLNbWT6vEVDiTSv4gMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);